### ISSUE TITLE
Can't edit cards

### ISSUE THREAD

**Issue by eryncerise** [db0company/SchoolIdolAPI#40]
When I click the icon that tells me a card is in my deck, I don't see the Edit Card popup anymore. The URL bar still says schoolido.lu/cards/#editCard after clicking the icon, though. The only way I'm able to change a card is to click the "Add Card" icon, click "Delete This Card" in that popup (which then takes me to a blank white page with a URL like http://schoolido.lu/ajax/deletecard/40087/), and then re-add the card with the new information.

**Comment by eryncerise** [comment]
Should also add: tried in Firefox, Safari, and Chrome. Doesn't work in any of them. I'm using OSX Yosemite (10.10.2).

**Comment by db0company** [comment]
Looks like the javascript is not working, which can be either that the page hasn't finished loading or that there is an error that stopped the script.
Can you open the javascript console and tell me if you see an error?

**Comment by db0company** [comment]
I think I fixed it, can you confirm?

**Comment by eryncerise** [comment]
Works now! Thanks! :)

**Comment by db0company** [comment]
Thank you for reporting this error ;)
