### ISSUE TITLE
UR Kotori Minami Promo card #204 no longer Japan only

### ISSUE THREAD

**Issue by OzzyOtaku** [db0company/SchoolIdolAPI#50]

**Comment by Wopian** [comment]
Also #207. Given out in same event.

http://schoolido.lu/cards/207/

**Comment by EsterCol** [comment]
And Maki #216, given in the next event

http://schoolido.lu/cards/216/

**Comment by db0company** [comment]
Thank you so much for reporting! We fixed this issue.
