### ISSUE TITLE
Card #538 Not Classified Under バレンタイン編 Collection

### ISSUE THREAD

**Issue by mrdrdj** [db0company/SchoolIdolAPI#56]
The Rin Pure UR card should be included in the バレンタイン編

Attached Image of the Rin card not showing
![card538](https://cloud.githubusercontent.com/assets/11417947/6590021/f8f68494-c7e4-11e4-9a37-a13ef9612a91.PNG)

**Comment by db0company** [comment]
Thanks for reporting!

However, we do not insert any information manually. All the information come from various wiki.
The information about the collection comes from this page: http://www59.atwiki.jp/lovelive-sif/pages/34.html

If you're willing to help about this (thanks!), can you please try to see if you can update this wiki page?

Unfortunately, we do not have time to update all the wikis ourselves :/

Thanks again.
